development:
  adapter: postgresql
  database: yubnub_dev
  host: localhost
  username: root
  password:

test:
  adapter: postgresql
  database: yubnub_test
  host: localhost
  username: root
  password:

production:
  adapter: postgresql
  database: yubnub_prod
  host: localhost
  username: jon_aquino
  password:

